export enum Currency {
    CZK = "CZK",
    AUD = "AUD",
    BRL =" BRL",
    BGN = "BGN",
    CAD = "CAD",
    CNY = "CNY",
    DKK = "DKK",
    EUR = "EUR",
    HKD = "HKD",
    HUF = "HUF",
    ISK = "ISK",
    XDR = "XDR",
    INR = "INR",
    IDR = "IDR",
    ILS = "ILS",
    JPY = "JPY",
    MYR = "MYR",
    MXN = "MXN",
    NZD = "NZD",
    NOK = "NOK",
    PHP = "PHP",
    PLN = "PLN",
    RON = "RON",
    SGD = "SGD",
    ZAR = "ZAR",
    KRW = "KRW",
    SEK = "SEK",
    CHF = "CHF",
    THB = "THB",
    TRY = "TRY",
    GBP = "GBP",
    USD = "USD"
}

export let dropDownValues =[
    {label: 'CZK', value: Currency.CZK},
    {label: 'AUD', value: Currency.AUD},
    {label: 'BRL', value: Currency.BRL},
    {label: 'BGN', value: Currency.BGN},
    {label: 'CAD', value: Currency.CAD},
    {label: 'CNY', value: Currency.CNY},
    {label: 'DKK', value: Currency.DKK},
    {label: 'EUR', value: Currency.EUR},
    {label: 'HKD', value: Currency.HKD},
    {label: 'HUF', value: Currency.HUF},
    {label: 'ISK', value: Currency.ISK},
    {label: 'XDR', value: Currency.XDR},
    {label: 'INR', value: Currency.INR},
    {label: 'IDR', value: Currency.IDR},
    {label: 'ILS', value: Currency.ILS},
    {label: 'JPY', value: Currency.JPY},
    {label: 'MYR', value: Currency.MYR},
    {label: 'MXN', value: Currency.MXN},
    {label: 'NZD', value: Currency.NZD},
    {label: 'NOK', value: Currency.NOK},
    {label: 'PHP', value: Currency.PHP},
    {label: 'PLN', value: Currency.PLN},
    {label: 'RON', value: Currency.RON},
    {label: 'SGD', value: Currency.SGD},
    {label: 'ZAR', value: Currency.ZAR},
    {label: 'KRW', value: Currency.KRW},
    {label: 'SEK', value: Currency.SEK},
    {label: 'CHF', value: Currency.CHF},
    {label: 'THB', value: Currency.THB},
    {label: 'TRY', value: Currency.TRY},
    {label: 'GBP', value: Currency.GBP},
    {label: 'USD', value: Currency.USD},
]